// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library parser.error_kind;

enum ErrorKind {
  EMPTY_NAMED_PARAMETER_LIST,
  EMPTY_OPTIONAL_PARAMETER_LIST,
  EXPECTED_BODY,
  EXPECTED_HEX_DIGIT,
  EXPECTED_OPEN_PARENS,
  EXPECTED_STRING,
  EXTRANEOUS_MODIFIER,
  EXTRANEOUS_MODIFIER_REPLACE,
  INVALID_AWAIT_FOR,
  INVALID_INPUT_CHARACTER,
  INVALID_SYNC_MODIFIER,
  INVALID_VOID,
  MALFORMED_STRING_LITERAL,
  MISSING_EXPONENT,
  POSITIONAL_PARAMETER_WITH_EQUALS,
  REQUIRED_PARAMETER_WITH_DEFAULT,
  UNMATCHED_TOKEN,
  UNSUPPORTED_PREFIX_PLUS,
  UNTERMINATED_COMMENT,
  UNTERMINATED_STRING,
  UNTERMINATED_TOKEN,

  UNSPECIFIED,
}
